[package]
name = "devsa/project-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ProfileService = "brittonfischer/profileservice@2.1.5"
RoactRodux = "roblox/roact-rodux@0.3.0"
Component = "sleitnick/component@2.4.6"
Promise = "evaera/promise@4.0.0"
Janitor = "howmanysmall/janitor@1.14.1"
Signal = "stravant/goodsignal@0.2.1"
Loader = "sleitnick/loader@2.0.0"
Rodux = "roblox/rodux@4.0.0-rc.0"
Roact = "roblox/roact@1.4.4"
Sift = "csqrl/sift@0.0.3"
Net = "vorlias/net@3.0.1"